# Mapping from aircraft type → operator group
# Values: "NATO": , "Non-NATO": , "Both"
# The mapping was created by Microsoft Copilot (2026-03-14)

OPERATOR_MAP = {
    "A10": "NATO",
    "A400M": "Both",
    "AG600": "Non-NATO",
    "AH64": "Both",
    "AKINCI": "Both",
    "AV8B": "NATO",
    "An124": "Non-NATO",
    "An22": "Non-NATO",
    "An225": "Non-NATO",
    "An72": "Non-NATO",
    "B1": "NATO",
    "B2": "NATO",
    "B52": "NATO",
    "Be200": "Non-NATO",
    "C1": "Non-NATO",
    "C130": "Both",
    "C17": "Both",
    "C2": "Non-NATO",
    "C390": "Both",
    "C5": "NATO",
    "CH47": "Both",
    "CH53": "Both",
    "CL415": "Both",
    "E2": "Both",
    "E7": "Both",
    "EF2000": "Both",
    "EMB314": "Non-NATO",
    "F117": "NATO",
    "F14": "Non-NATO",
    "F15": "Both",
    "F16": "Both",
    "F18": "NATO",
    "F2": "Non-NATO",
    "F22": "NATO",
    "F35": "Both",
    "F4": "Non-NATO",
    "FCK1": "Non-NATO",
    "H6": "Non-NATO",
    "Il76": "Non-NATO",
    "J10": "Non-NATO",
    "J20": "Non-NATO",
    "J35": "Non-NATO",
    "J36": "Non-NATO",
    "JAS39": "Both",
    "JF17": "Non-NATO",
    "JH7": "Non-NATO",
    "KAAN": "NATO",
    "KC135": "NATO",
    "KF21": "Non-NATO",
    "KJ600": "Non-NATO",
    "Ka27": "Non-NATO",
    "Ka52": "Non-NATO",
    "MQ9": "Both",
    "Mi24": "Both",
    "Mi26": "Non-NATO",
    "Mi28": "Non-NATO",
    "Mi8": "Non-NATO",
    "Mig29": "Both",
    "Mig31": "Non-NATO",
    "Mirage2000": "Both",
    "P3": "Both",
    "RQ4": "Both",
    "Rafale": "Both",
    "SR71": "NATO",
    "Su24": "Non-NATO",
    "Su25": "Non-NATO",
    "Su34": "Non-NATO",
    "Su47": "Non-NATO",
    "Su57": "Non-NATO",
    "TB001": "Non-NATO",
    "TB2": "NATO",
    "Tejas": "Non-NATO",
    "Tornado": "Both",
    "Tu160": "Non-NATO",
    "Tu22M": "Non-NATO",
    "Tu95": "Non-NATO",
    "U2": "NATO",
    "UH60": "Both",
    "US2": "Non-NATO",
    "V22": "Both",
    "Vulcan": "NATO",
    "WZ7": "Non-NATO",
    "X32": "NATO",
    "XB70": "NATO",
    "Y20": "Non-NATO",
    "YF23": "NATO",
    "Z10": "Non-NATO",
    "Z19": "Non-NATO"
}

def get_operator(class_id: int, class_names: list[str]) -> str:
    """Return operator group (NATO / Non-NATO / Both) for a given class ID."""
    name = class_names[class_id]
    return OPERATOR_MAP.get(name, "Unknown")
